name=ESP32 BLE Mouse
version=0.0.1
author=ba1azs
maintainer=ba1azs
sentence=Bluetooth LE Mouse library for the ESP32.
paragraph=Bluetooth LE Mouse library for the ESP32.
category=Communication
url=https://github.com/ba1azs/esp32-ble-mouse
architectures=esp32
